# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='post.proto',
  package='post',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\npost.proto\x12\x04post\"$\n\x11PostCreateRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\" \n\x12PostCreateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"c\n\x10PostListResponse\x12*\n\x05posts\x18\x01 \x03(\x0b\x32\x1b.post.PostListResponse.Post\x1a#\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\tb\x06proto3')
)




_POSTCREATEREQUEST = _descriptor.Descriptor(
  name='PostCreateRequest',
  full_name='post.PostCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='post.PostCreateRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=56,
)


_POSTCREATERESPONSE = _descriptor.Descriptor(
  name='PostCreateResponse',
  full_name='post.PostCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='post.PostCreateResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=90,
)


_POSTLISTRESPONSE_POST = _descriptor.Descriptor(
  name='Post',
  full_name='post.PostListResponse.Post',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='post.PostListResponse.Post.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='post.PostListResponse.Post.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=191,
)

_POSTLISTRESPONSE = _descriptor.Descriptor(
  name='PostListResponse',
  full_name='post.PostListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='posts', full_name='post.PostListResponse.posts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_POSTLISTRESPONSE_POST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=191,
)

_POSTLISTRESPONSE_POST.containing_type = _POSTLISTRESPONSE
_POSTLISTRESPONSE.fields_by_name['posts'].message_type = _POSTLISTRESPONSE_POST
DESCRIPTOR.message_types_by_name['PostCreateRequest'] = _POSTCREATEREQUEST
DESCRIPTOR.message_types_by_name['PostCreateResponse'] = _POSTCREATERESPONSE
DESCRIPTOR.message_types_by_name['PostListResponse'] = _POSTLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PostCreateRequest = _reflection.GeneratedProtocolMessageType('PostCreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _POSTCREATEREQUEST,
  __module__ = 'post_pb2'
  # @@protoc_insertion_point(class_scope:post.PostCreateRequest)
  ))
_sym_db.RegisterMessage(PostCreateRequest)

PostCreateResponse = _reflection.GeneratedProtocolMessageType('PostCreateResponse', (_message.Message,), dict(
  DESCRIPTOR = _POSTCREATERESPONSE,
  __module__ = 'post_pb2'
  # @@protoc_insertion_point(class_scope:post.PostCreateResponse)
  ))
_sym_db.RegisterMessage(PostCreateResponse)

PostListResponse = _reflection.GeneratedProtocolMessageType('PostListResponse', (_message.Message,), dict(

  Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), dict(
    DESCRIPTOR = _POSTLISTRESPONSE_POST,
    __module__ = 'post_pb2'
    # @@protoc_insertion_point(class_scope:post.PostListResponse.Post)
    ))
  ,
  DESCRIPTOR = _POSTLISTRESPONSE,
  __module__ = 'post_pb2'
  # @@protoc_insertion_point(class_scope:post.PostListResponse)
  ))
_sym_db.RegisterMessage(PostListResponse)
_sym_db.RegisterMessage(PostListResponse.Post)


# @@protoc_insertion_point(module_scope)
